env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - import
  - '@emotion'
rules:
  indent:
    - 1
    - 2
  comma-dangle:
    - 1
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  "@typescript-eslint/comma-dangle":
    - 1
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  "@typescript-eslint/semi":
    - error
    - never
  semi:
    - error
    - never
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/jsx-props-no-spreading: 0
  react/jsx-one-expression-per-line: 0
  react/state-in-constructor: 0
  import/no-unresolved: 0
  react/jsx-fragments:
    - 1
    - element
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - hrefLeft
        - hrefRight
      aspects:
        - invalidHref
        - preferButton
settings:
  react:
    version: detect
  import/resolver:
    node:
      moduleDirectory:
        - node_modules